version: '3.8'
services:
  vpn-ssh:
    build: .
    container_name: vpn-with-ssh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - ENCRYPTION_KEY_FILE=/run/secrets/encryption_key
      - PASSWORD_PREFIX=52
      - VPN_USERNAME=tt_ship
      - OVPN_CONFIG=/etc/openvpn/client.ovpn
      - SSH_HOST=your-ssh-server.com
      - SSH_PORT=22
      - SSH_USER=your-username
      - HTTP_PROXY_PORT=8888
      - SOCKS_PROXY_PORT=1080
      - HTTP_PROXY_PORT_2=8889
      - SOCKS_PROXY_PORT_2=1081
      - PROXY_ALLOW_NETWORK=127.0.0.1 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12
      - VPN_ROUTES=192.168.10.0/24,10.8.0.0/24
    volumes:
      - ./client.ovpn:/etc/openvpn/client.ovpn
      - ./otp_secret.enc:/etc/openvpn/otp_secret.enc
      - ./ssh-key:/root/.ssh/id_rsa
      - ./known_hosts:/root/.ssh/known_hosts
    ports:
      - "8888:8888"   # Основной HTTP proxy
      - "1080:1080"   # Основной SOCKS proxy
      - "8889:8889"   # Дополнительный HTTP proxy
      - "1081:1081"   # Дополнительный SOCKS proxy
    restart: unless-stopped
